import type { Metadata } from "next";
import StyledComponentsWrapper from "@/components/StyledComponentsWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Nanum+Square:wght@400;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body>
        <StyledComponentsWrapper>{children}</StyledComponentsWrapper>
      </body>
    </html>
  );
}
